{
 "title": "Senhas",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "SENHAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tamanho da memória residente em bytes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{container=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "python_info{endpoint=\"5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tamanho da memória virtual em bytes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_virtual_memory_bytes{namespace=\"giropops-senhas\", container=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de senhas geradas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(senha_gerada_total{container=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo total de CPU gasto em segundos",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max(process_cpu_seconds_total{container=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de início do processo em segundos",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{container=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}